### ISSUE TITLE
Update listing entities and DTO models with properties for company logo id and date for last apply

### ISSUE THREAD

**Issue by RasmusBroborg** [JohanSaisa/GT#106]

**Comment by OscarThorburn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US3002: Admin - Ange sista ansökningsdag](https://trello.com/c/i8KTMGOx/59-us3002-admin-ange-sista-ans%C3%B6kningsdag)

**Comment by OscarThorburn** [comment]
Decided to move CompanyLogoId to the company entity since this makes more sence. Each company should have an image attached to it not the listings.
