### ISSUE TITLE
Functionality for admin to  add last application date on listings

### ISSUE THREAD

**Issue by KristofferHogberg** [JohanSaisa/GT#107]
Data layer: Update entities and migrate.
Core layer: Update AddAsync, Update and DTO
UI Layer: Display updated DTO

**Comment by RasmusBroborg** [comment]
Duplicate. See issue #106. This issue could perhaps be relabeled for implementations in UI and Core layer?

**Comment by OscarThorburn** [comment]
Core layer: Update AddAsync.
Entities and DTOs is solved in issue https://github.com/JohanSaisa/GT/issues/106.

**Comment by OscarThorburn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US3002: Admin - Ange sista ansökningsdag](https://trello.com/c/i8KTMGOx/59-us3002-admin-ange-sista-ans%C3%B6kningsdag)
