### ISSUE TITLE
Create Unit testing for ExperienceLevelService

### ISSUE THREAD

**Issue by OscarThorburn** [JohanSaisa/GT#147]
- [x] AddAsync
- [x] ExistsByNameAsync
- [x] GetAllAsync
- [ ] DeleteAsync
- [ ] GetByIdAsync
- [ ] UpdateAsync

**Comment by OscarThorburn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US4004: Developer - Test experience level](https://trello.com/c/WQu1ZluI/4-us4004-developer-test-experience-level)

**Comment by RasmusBroborg** [comment]
Accidentally closed issue when merging PR which only contained partial solution to issue. Reopening issue and branch.

**Comment by RasmusBroborg** [comment]
Reopening issue to address previously missed methods in service.
