### ISSUE TITLE
Migrate controllers to seperate API project

### ISSUE THREAD

**Issue by OscarThorburn** [JohanSaisa/GT#148]
- [x] Create API project
- [x] Migrate Experience Level Controller
- [x] Migrate Listing Controller
- [x] Migrate Company Controller
- [x] Migrate Inquiry Controller
- [x] Migrate Auth Controller

**Comment by OscarThorburn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dev - Listing API](https://trello.com/c/t2jTJlQG/7-dev-listing-api)

**Comment by JohanSaisa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dev - Auth API](https://trello.com/c/C59LA1Pd/9-dev-auth-api)

**Comment by OscarThorburn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dev - Experience Level API](https://trello.com/c/fUteoqzD/5-dev-experience-level-api)

**Comment by JohanSaisa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US4005: Dev - Company API](https://trello.com/c/ZFpJQbJI/6-us4005-dev-company-api)
