### ISSUE TITLE
Refactor SaveChangesAsync to separate method

### ISSUE THREAD

**Issue by JohanSaisa** [JohanSaisa/GT#182]

**Comment by JohanSaisa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US5002: Refactor SaveAsync in Repo](https://trello.com/c/Ovr9x0Wk/19-us5002-refactor-saveasync-in-repo)

**Comment by RasmusBroborg** [comment]
Fix in major refactoring issue.
