### ISSUE TITLE
Add basic API ListingController

### ISSUE THREAD

**Issue by OscarThorburn** [JohanSaisa/GT#58]
Through API controllers. Testing with postman is enough for now since this will work with SPA later

**Comment by OscarThorburn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Admin - Lägga till annons](https://trello.com/c/cwehLJmQ/33-admin-l%C3%A4gga-till-annons)

**Comment by OscarThorburn** [comment]
Through API controllers. Testing with postman is enough for now since this will work with SPA later

**Comment by JohanSaisa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Baseline Project -- N-Tier Architecture](https://trello.com/c/YXJK8QOY/45-baseline-project-n-tier-architecture)

**Comment by OscarThorburn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US1003: Admin - Redigera annons](https://trello.com/c/VJ0OFzFj/36-us1003-admin-redigera-annons)
