### ISSUE TITLE
Update entities for DB models and DTOs

### ISSUE THREAD

**Issue by JohanSaisa** [JohanSaisa/GT#65]
- [x] Add property in listing entity and DTO for last application date, id for company logo image
- [x] Review which properties should be unique (e.g. Location Name)
- [x] Review which properties should be nullable (e.g. FilterDTO)
- [x] Update properties with appropriate annotations
- [ ] Find solution for FK restraint which keeps the database from deleting a Listing if a ListingInquiry has a FK referencing the Listing.
- [x] Add LinkedIn link to ApplicationUser ?
- [x] Migrate database(s)

**Comment by RasmusBroborg** [comment]
"Find solution for FK restraint which keeps the database from deleting a Listing if a ListingInquiry has a FK referencing the Listing." - May not be relevant as this is handled manually by the ListingService.

**Comment by RasmusBroborg** [comment]
"Review which properties should be nullable (e.g. FilterDTO)" - All properties except Id's should be nullable without breaking the application. Helps the database administrator as well as encourages building a solid application.
