### ISSUE TITLE
Bugfixes in Listing Service

### ISSUE THREAD

**Issue by RasmusBroborg** [JohanSaisa/GT#81]
The following bugs have been identified in ListingService.cs:

**When creating a new listing:**
- [x] The property CreatedDate is always null

**When updating a listing:** 
- [x] Keeps old company and does not create and assign a new. 
- [x] Experience level gets added to the db but id is not applied to the updated listing.

**When deleting a listing:**
- [ ] Does not work with listings which have a connected ListingInquiry. Appears to be a problem with cascading delete.
`The DELETE statement conflicted with the REFERENCE constraint "FK_ListingInquiries_Listings_ListingId". The conflict occurred in database "GTAppDb", table "dbo.ListingInquiries", column 'ListingId'.`

**When calling the GetAsync() method using the filter:**
- [ ] Does not filter by jobtitle
- [ ] Keywords filter property do not search for matches in listingTitle, Employer, ExperienceLevel
- [ ] ExperienceLevels filter property do not filter by anything. Always returns everything
- [ ] Shows no results when Location is set to an empty string in JSON. All other paramaters can be set to an empty string in JSON ("").

```
    //Returns nothing when passed in as JSON input:
    "Location" : ""
    
    //Returns all matches when passed in as JSON input:
    "fte": "",
    "salaryMin": "",
    "salaryMax": "",
    "ExperienceLevels" : [],
    "jobTitle" : ""
```

**Comment by RasmusBroborg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US1005: Create initial Services in Core layer needed to create listings.](https://trello.com/c/Bu1ENTKE/50-us1005-create-initial-services-in-core-layer-needed-to-create-listings)

**Comment by antoncarlgren** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US2005: Användare - Sortering & Filtrering](https://trello.com/c/wGniKsNk/35-us2005-anv%C3%A4ndare-sortering-filtrering)
